<GUI>:
    rows: 4
    TextInput:
        size_hint: 1, 0.1
        multiline: False
        font_size: 40

    BoxLayout:

        Scatter:
            do_rotation: False
            Image:
                pos_hint: {'center_x': 1, 'center_y': 1}
                source: '123.jpg'

    GridLayout:
        background_normal: ''
        backgroud_color: (1, 1, 1, 0)
        cols: 2
        pos_hint: {'center_x': 1, 'center_y': 0}
        Button:
            size_hint: None,None
            size: 64,64
            text: "gi"
        Button:
            size_hint: None,None
            size: 64,64
            text: "gi"