GUI:
<GUI>:
    size: root.size
    pos: root.pos


    GridLayout:
        cols: 5
        BoxLayout:
            Scatter:
                do_rotation: False
                Image:
                    pos_hint: {'center_x': 1, 'center_y': 1}
                    size: 100,164
                    source: '123.jpg'
        TextInput:
            size_hint: 1, 0.2
            multiline: False
            font_size: 40
        Button:
            size_hint: None,None
            size: 64,64
            text: "gi"
        Button:
            size_hint: None,None
            size: 64,64
            text: "gi"

