BoxLayoutExample:
<BoxLayoutExample>:
    orientation: 'vertical'
    Button:
        text: 'A'
        # size: '40dp', '40dp'
        size_hint: 0.5, None
        width: '40dp'
        pos_hint: {'right': 1}
    Button:
        text: 'B'
    Label:
        text: 'C'

<MainWidget>:
    Button:
        text: 'hello'
        color: 1, 0, 0, 1
    Label:
        text: 'word'
        size: '100dp', '80dp'
        pos: '200dp', '300dp'
        color: 1, 1, 0, 1
